/**
 * False-positive battery: commands a developer runs dozens of times a day.
 * None of them may produce a needsReview or critical match.
 * (Informational matches such as remote downloads are tolerated.)
 */
import { describe, expect, it } from "vitest";
import { scanCommand } from "../src/core/matcher.js";
import { RULES, RULES_BY_ID } from "../src/core/rules.js";

// Ensure the recommendation list is trustworthy: these really are benign.
const BENIGN_COMMANDS: string[] = [
  "ls",
  "ls -la",
  "pwd",
  "clear",
  "cat package.json",
  "cat README.md",
  "head -20 src/main.ts",
  "tail -f logs/app.log",
  "echo hello world",
  "echo $PATH",
  "env | sort",
  "uname -a",
  "date",
  "df -h",
  "uptime",
  "whoami",
  "git status",
  "git log --oneline -10",
  "git diff --stat",
  "git pull",
  "git push origin main",
  "git push --tags",
  "git branch",
  "git branch -a",
  "git branch -d merged",
  "git stash list",
  "git stash show -p",
  "git tag -l",
  "git tag v1.0.0",
  "git clean -n",
  "git clean -nd",
  "git reset --soft HEAD~1",
  "git reset HEAD file.ts",
  "git add src/",
  "git add README.md package.json",
  "git commit --amend --no-edit",
  "git commit -m 'feat: build parser'",
  "git fetch origin",
  "git show HEAD~1 --stat",
  "git checkout -b feature/x",
  "git merge --no-ff feature/x",
  "git mv old.ts new.ts",
  "git cherry-pick abc1234",
  "git rebase main",
  "git reflog",
  "git fsck",
  "git gc",
  "npm install",
  "npm install -g pnpm",
  "npm run build",
  "npm run test",
  "npm test",
  "npx tsc --noEmit",
  "npm cache clean",
  "npm remove lodash",
  "bun install",
  "bun remove left-pad",
  "pnpm install",
  "pnpm dev",
  "yarn build",
  "yarn install",
  "python3 -c 'print(1)'",
  "python3 script.py --output build",
  "python3 -c \"import shutil; shutil.copy('a','b')\"",
  "python3 -c \"import os; print(os.getcwd())\"",
  "pip install pytest",
  "pip list",
  "uv pip install fastapi",
  "node -e 'console.log(1)'",
  "node -e \"fs.writeFileSync('/tmp/out.txt','x')\"",
  "node -e \"fs.mkdirSync('build')\"",
  "node -e \"console.log(require('fs').readdirSync('.'))\"",
  "node server.js",
  "deno run main.ts",
  "bun run dev",
  "tsc --noEmit",
  "clang main.c -o main",
  "gcc -Wall hello.c -o hello",
  "go build ./...",
  "go test ./...",
  "cargo build",
  "cargo test",
  "rustc main.rs",
  "make build",
  "make test",
  "cmake ..",
  "mvn -q clean compile",
  "gradle test",
  "dotnet build",
  "rsync -av ./dist/ /tmp/dist/",
  "cp foo.js bar.js",
  "cp -r dist build",
  "cp notes.txt /tmp/",
  "cp config.example.json config.json",
  "mv src/a.ts src/b.ts",
  "mv build/out dist",
  "mv notes.txt /tmp/notes.bak",
  "mv a b",
  "mkdir -p src/components",
  "touch /tmp/empty",
  "find . -name '*.ts'",
  "find . -type f -print0",
  "find . -name '*.log' -ls",
  "grep -r TODO src",
  "rg -l console.log src",
  "ls | xargs echo",
  "ls *.ts | wc -l",
  "sort users.txt | uniq -c",
  "awk '{print $1}' data.txt",
  "sed -i 's/foo/bar/g' /tmp/x.txt",
  "curl -s https://api.example.com/health",
  "curl -s https://example.com/data.json -o data.json",
  "curl -o /tmp/file.tgz https://example.com/file.tgz",
  "wget -O /tmp/x https://example.com/archive.zip",
  "kubectl get pods",
  "kubectl describe pod x",
  "kubectl logs -f deploy/api",
  "kubectl apply -f deploy.yaml",
  "docker ps",
  "docker images",
  "docker compose ps",
  "docker compose down",
  "docker system df",
  "docker network ls",
  "docker volume ls",
  "docker build -t myapp .",
  "docker run -it alpine",
  "docker system prune",
  "aws s3 ls",
  "aws s3 cp file.txt s3://bucket/",
  "aws ec2 describe-instances",
  "aws ec2 stop-instances --instance-ids i-xxxx",
  "gcloud compute instances list",
  "gcloud sql instances describe prod-db",
  "az group list",
  "systemctl status docker",
  "systemctl restart nginx",
  "systemctl is-active sshd",
  "systemctl list-units",
  "systemctl enable docker",
  "service nginx restart",
  "service docker status",
  "service --status-all",
  "crontab -l",
  "crontab -e",
  "ip link show",
  "ip addr show",
  "ip route show",
  "route -n",
  "ifconfig",
  "nmcli device status",
  "nmcli connection up eth0",
  "iptables -L",
  "iptables -S",
  "ufw status",
  "sudo ufw allow 22/tcp",
  "ufw --help",
  "ps aux | grep node",
  "top -b -n 1",
  "kill 1234",
  "kill -TERM 42",
  "kill -l",
  "chmod +x script.sh",
  "chmod 644 file.txt",
  "chmod 600 .env.local",
  "chmod a-x setup",
  "chmod -R u+rw,g+r,o-rwx src",
  "chown user:group file.txt",
  "chgrp dev src",
  "lsattr /tmp/x",
  "watch -n 5 df -h",
  "tail -n 100 data.log | less",
  "cat <<EOF | sort\nbeta\nalpha\nEOF",
  "echo hi > /tmp/notes.txt",
  "date > /tmp/today.log",
  "ls > /tmp/list.txt",
  "echo bye >> README.md",
  "> /dev/null echo hi",
  "cat /dev/null > /tmp/sink",
  "blkid",
  "lsblk",
  "df /dev/sda1",
  "findmnt",
  "truncate -s 100M /tmp/test.bin",
  "openssl version",
  "ssh -V",
  "git ls-remote origin",
  "gitremote() { echo hi; }",
];

const OBVIOUSLY_SAFE = ["unset FOO", "ldconfig -p", "lsusb", "lspci", "free -h", "vmstat 1 2", "iostat"];

describe("false-positive battery", () => {
  for (const cmd of [...BENIGN_COMMANDS, ...OBVIOUSLY_SAFE]) {
    it(`does not flag: ${cmd}`, () => {
      const res = scanCommand(cmd);
      const severe = [...res.critical, ...res.needsReview];
      expect(
        severe.map((m) => m.rule.id),
        `benign command must not be flagged: ${cmd}`,
      ).toEqual([]);
    });
  }

  it("registry has no duplicate id collisions across categories", () => {
    const seen = new Set<string>();
    for (const rule of RULES) {
      expect(seen.has(rule.id)).toBe(false);
      seen.add(rule.id);
    }
    expect(RULES_BY_ID.size).toBe(RULES.length);
  });
});